name = "game-api"
compatibility_date = "2023-03-23"

account_id = "af658a349862d1cffaf575181ddcb474"
workers_dev = true # or zone_id = "<ZONE ID>" if you have one

main = "build/index.mjs"

[build]
command = "npm run build"

[vars]
REALM_APPID = "text-adventure-maker-pcbeb"
