name: Deploy to Firebase Hosting on PR
'on':
  pull_request:
    paths:
    - 'text-adventure-creator/**'
jobs:
  build_test_and_preview:
    name: Build, test and preview
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: text-adventure-creator
      - run: npm run build
        working-directory: text-adventure-creator
      - run: npm test
        working-directory: text-adventure-creator
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEXTUAL_ADVENTURE_CREATOR }}'
          channelId: preview
          projectId: textual-adventure-creator
          entryPoint: text-adventure-creator
