name: Deploy to Firebase Hosting on PR
'on':
  pull_request:
    paths:
    - 'text-adventure-creator/**'
    ignore_paths:
    - 'text-adventure-creator/src/functions/**'
jobs:
  build_and_preview_creator:
    name: Creator build, test and preview
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18.14.2
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: text-adventure-creator
      - name: Build creator
        run: npm run build
        working-directory: text-adventure-creator
      - name: Run tests
        run: npm test --debug
        working-directory: text-adventure-creator
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEXTUAL_ADVENTURE_CREATOR }}'
          projectId: textual-adventure-creator
          entryPoint: text-adventure-creator
